name: Telegram Push Notify
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        run: |
          MSG="🚀 New push by ${{ github.actor }} to ${{ github.repository }}
          Commit message: ${{ github.event.head_commit.message }}"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.8412632876:AAF-LYtrVEiOJrvXyzg0hQq4tLO4cpNa1Ns }}/sendMessage \
          -d chat_id=${{ secrets.1377500517 }} \
          -d text="$MSG"
