name: Notify via Telegram

on:
  push:
    branches:
      - main  # or add more branches here if you want
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          URL="${{ github.event.head_commit.url }}"

          MESSAGE="📢 *${AUTHOR}* pushed to *${REPO}* on branch *${BRANCH}* \n\n💬 Commit: ${COMMIT_MESSAGE}\n🔗 [View Commit](${URL})"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="Markdown" \
            -d text="$MESSAGE"
