name: Notify via Telegram

on:
  push:
    branches:
      - main
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          MESSAGE=" New push to *${REPO}* by *${AUTHOR}* on branch *${BRANCH}*\n\n Commit: ${COMMIT_MESSAGE}"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="Markdown" \
            -d text="$MESSAGE"
